steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/laah-cybernetics/vllm-streamer:latest', '-f', 'deployment/docker/Dockerfile.vllm', '.']
images:
- 'gcr.io/laah-cybernetics/vllm-streamer:latest'
